export const RESET_CONTENT = "RESET_CONTENT";

export const INCREMENT_LENGTH = "INCREMENT_LENGTH";
export const DECREMENT_LENGTH = "DECREMENT_LENGTH";

export const CALCULATE_REMAINING = "CALCULATE_REMAINING";
export const START_STOP_TIMER = "START_STOP_TIMER";
